### ISSUE TITLE
minor edits for event table

### ISSUE THREAD

**Issue by sbeaulieu** [CeNCOOS/OBIS_workshop_2024_IFCB#11]
datasetName has an extra "/" in the middle
samplingProtocol spelling errors: Methods section "IFCB shore station" from Fischer, A., et al. (2020) https://doi.org/10.1002/lno.11443
thanks

**Comment by flbahr** [comment]
Stace, 
I hope to get to this soon. I've got a couple of other projects that have come up that need to be dealt with. 
(Also got trained on the IPT the other day) 
Cheers, 
Fred 


From: "Stace Beaulieu" ***@***.***> 
To: "CeNCOOS" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Tuesday, June 18, 2024 1:50:48 PM 
Subject: [CeNCOOS/OBIS_workshop_2024_IFCB] minor edits for event table (Issue #11) 





datasetName has an extra "/" in the middle 
samplingProtocol spelling errors: Methods section "IFCB shore station" from Fischer, A., et al. (2020) [ https://doi.org/10.1002/lno.11443 | https://doi.org/10.1002/lno.11443 ] 
thanks

**Comment by flbahr** [comment]
Slash removed in code and spelling error fixed.
