### ISSUE TITLE
environment.yml file is generated from base environment

### ISSUE THREAD

**Issue by patcdaniel** [CeNCOOS/OBIS_workshop_2024_IFCB#15]
@flbahr The .yml file you generated looks like it was generated from you base conda environment, not a the obis_ifcb environment. I generated a new one from a fresh install and also added a requirement.txt file for a pip install based on the freshly made environment.

**Comment by patcdaniel** [comment]
I ended up uploading a different environment.yml file, that should build a working environment.

**Comment by flbahr** [comment]
Patrick, 
Thank you! 
Cheers, 
Fred
