### ISSUE TITLE
add comment for IFCB triggering into code cell to generate emof table

### ISSUE THREAD

**Issue by sbeaulieu** [CeNCOOS/OBIS_workshop_2024_IFCB#17]
in notebook getSantaCruzdata.ipynb
please comment as placeholder for work that could be done in the future
When calculating concentrations (per volume analyzed), triggering solely on autofluorescence is likely to underestimate taxa not containing chlorophyll.
Triggering solely on autofluorescence can be determined with function get_ifcb_metadata using dict_keys 'PMTtriggerSelection_DAQ_MCConly' 
When 'PMTtriggerSelection_DAQ_MCConly' = 2, a statement regarding underestimate can be added into the emof table 'measurementRemarks' for 'measurementType':'Abundance...' and 'measurementType':'Biovolume...'

also see https://github.com/sccoos/OBIS_workshop_2023_IFCB/issues/1

**Comment by flbahr** [comment]
Added a code/comment cell above the code that created the EMOF table.

**Comment by sbeaulieu** [comment]
thanks
