### ISSUE TITLE
add to notebook a string variable for path to local files

### ISSUE THREAD

**Issue by sbeaulieu** [CeNCOOS/OBIS_workshop_2024_IFCB#3]
I recommend earlier to specify a string variable for path to local files. We load separately two local files 1 for the standardization of class names and 1 for thresholds.

**Comment by sbeaulieu** [comment]
this will also be important to specify path for output csv files (may not be the same path)

**Comment by flbahr** [comment]
Stace, 
I've got a set up for the path for the input files and will add an output path but I've not pushed to gitHub yet. 
Fred

**Comment by patcdaniel** [comment]
I worked on cleaning up the repo a little bit and was working in the [getSantaCruzdata_update.ipynb](https://github.com/CeNCOOS/OBIS_workshop_2024_IFCB/blob/notebook_cleanup/notebooks/getSantaCruzdata_update.ipynb) notebook. Within that I changed some of the code to use relative paths.

**Comment by flbahr** [comment]
Okay...

**Comment by flbahr** [comment]
Since the code is now using relative paths.  I'm going to mark this as closed.
