### ISSUE TITLE
First Pass cleanup

### ISSUE THREAD

**Issue by patcdaniel** [CeNCOOS/OBIS_workshop_2024_IFCB#4]
Hi All,

I spent a couple of hours over the weekend looking at the repo and organizing things into the way that makes sense to my brain. I wanted to push it to the repo before it gets too far behind the main repo. 

I was mainly working out of the getSantaCruzdata_update.ipynb notebook and if that is ok, then I think we should just delete the other notebook and change the name to not have _update in it.

Fred, I also rewrote some of the functions to have formatted docstrings and I tried to use some of the markdown formatting to organize things.

I only made it about halfway down the notebook, so it still needs more work so I wanted to see what you all thought, if this is the direction you want to do, I can't submit a pull request for the branch before things get too divergent. 

best,
Patrick

**Comment by flbahr** [comment]
Patrick, 
I'm fine with it but I had it set up for my PC so I'm not sure how well relative paths work but push to the repro as you want. 
I didn't do anything to it over the weekend. 
Fred 


From: "Patrick Daniel" ***@***.***> 
To: "CeNCOOS" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Monday, April 29, 2024 9:36:57 AM 
Subject: [CeNCOOS/OBIS_workshop_2024_IFCB] First Pass cleanup (Issue #4) 






[POSSIBLE IMPERSONATION: This message is using the name of an MBARI account holder and has originated from outside of the organization. Please review the content and sender information carefully.] 

Hi All, 

I spent a couple of hours over the weekend looking at the repo and organizing things into the way that makes sense to my brain. I wanted to push it to the repo before it gets too far behind the main repo. 

I was mainly working out of the getSantaCruzdata_update.ipynb notebook and if that is ok, then I think we should just delete the other notebook and change the name to not have _update in it. 

Fred, I also rewrote some of the functions to have formatted docstrings and I tried to use some of the markdown formatting to organize things. 

I only made it about halfway down the notebook, so it still needs more work so I wanted to see what you all thought, if this is the direction you want to do, I can't submit a pull request for the branch before things get too divergent. 

best, 
Patrick

**Comment by flbahr** [comment]
With Patrick's clean up at this point.  I think this issue can be closed as he had pushed the code to the repo.
