### ISSUE TITLE
minor edits for occurrence table

### ISSUE THREAD

**Issue by sbeaulieu** [CeNCOOS/OBIS_workshop_2024_IFCB#7]
Some minor edits for occurrence table:

- scienfificName spelling revise to scientificName 
- scientificID revise to scientificNameID
- identificationReferences (I think this is in 2 places in the notebook):
  - Software to interpret autoclass scores: https://github.com/CeNCOOS/OBIS_workshop_2024_IFCB [Add which script or function]
  - Replace with: Software to interpret autoclass scores: https://github.com/CeNCOOS/OBIS_workshop_2024_IFCB/blob/main/notebooks/getSantaCruzdata.ipynb
- occurrenceStatus lowercase present
- For occurrenceID remove the .0 that is added to the AphiaID

thanks!

**Comment by flbahr** [comment]
Fixed ScientificName spelling, updated ScientificNameID, changed Present to present.  Removed trailing .0 from AphiaIDs.

**Comment by flbahr** [comment]
updated identificationReferences with above information and used PEP8 format for making the long line more legible (i.e. string is over multiple lines in code but still treated as one long line in the output.    This is the last of the changes above.  Closing issue.
