### ISSUE TITLE
minor edits to consider for event table

### ISSUE THREAD

**Issue by sbeaulieu** [CeNCOOS/OBIS_workshop_2024_IFCB#8]
sampleSizeValue and sampleSizeUnit are no longer needed in event table since that information is included in emof table

**Comment by sbeaulieu** [comment]
also we should consider more fully citing the paper referenced in samplingProtocol, for example: Methods section "IFCB shore station" from Fischer, A., et al. (2020) https://doi.org/10.1002/lno.11443

**Comment by flbahr** [comment]
removed SampleSizeVlaue and SampleSizeUnit from event table and have amended  reverence as given above.
