### ISSUE TITLE
minor edits for emof table

### ISSUE THREAD

**Issue by sbeaulieu** [CeNCOOS/OBIS_workshop_2024_IFCB#9]
- measurementRemarks for Biovolume please change to conversion factor 2.7 pixels per micron
- Consider truncating or rounding measurementValue for Abundance and Biovolume 
- We’ll need to change the measurementType for Biovolume if no longer using feature Biovolume but rather by calculation aligned to that in Pelagic Size Structure Database (PSSdb)
- Spelling measurementUnit Millilitres
- Consider filling the Not applicable unit for the instrument since that is in DL6.4-JERICO-S3-Best-practices 
Thanks!

**Comment by flbahr** [comment]
Fixed Millilitres spelling.

**Comment by flbahr** [comment]
Added conversion factor 2.7 pixels per micron for the biovolume measurement remarks

**Comment by flbahr** [comment]
Not sure I understand where the "not applicable" is to be put in the emof file.  
Are we talking about the "row1" measurementUnit and measurmentUnitID? @sbeaulieu

**Comment by sbeaulieu** [comment]
yes, in the row for measurementType Sampling Instrument Name, see DL6.4-JERICO-S3-Best-practices Table 2.2, thanks

**Comment by flbahr** [comment]
All issues addressed but the rounding issue.  Not sure how much we want to round/truncate.

**Comment by sbeaulieu** [comment]
for rounding measurementValue for abundance and biovolume concentrations: I suggest start with 3 decimal places since that appears to be what the volume analyzed is provided to
for the instrument measurementUnitID: please replace with https://vocab.nerc.ac.uk/collection/P06/current/XXXX/
thanks

**Comment by flbahr** [comment]
Should have resolved all parts of this issue.  Added rounding code.
